<a href="https://colab.research.google.com/github/Dipseenadmello07/Encryptix/blob/main/Encryptix_Task_3_(Credit_card_fraud_detection).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [7]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63472 entries, 0 to 63471
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    63472 non-null  int64
 1   V1      63472 non-null  float64
 2   V2      63472 non-null  float64
 3   V3      63472 non-null  float64
 4   V4      63472 non-null  float64
 5   V5      63472 non-null  float64
 6   V6      63472 non-null  float64
 7   V7      63472 non-null  float64
 8   V8      63472 non-null  float64
 9   V9      63472 non-null  float64
 10  V10     63471 non-null  float64
 11  V11     63471 non-null  float64
 12  V12     63471 non-null  float64
 13  V13     63471 non-null  float64
 14  V14     63471 non-null  float64
 15  V15     63471 non-null  float64
 16  V16     63471 non-null  float64
 17  V17     63471 non-null  float64
 18  V18     63471 non-null  float64
 19  V19     63471 non-null  float64
 20  V20     63471 non-null  float64
 21  V21     63471 non-null  float64
 22  V22     63471 non-null  float64
 23  V23     63471 non-null  float64
 24  V24     63471 non-null  float64
 25  V25     63471 non-null  float64
 26  V26     63471 non-null  float64
 27  V27     63471 non-null  float64
 28  V28     63471 non-null  float64
 29  Amount  63471 non-null  float64
 30  Class   63471 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 15.0 MB

In [9]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [13]:
credit_card_data = credit_card_data.dropna()

In [14]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [15]:
credit_card_data['Class'].value_counts()

Class
0.0    63306
1.0      165
Name: count, dtype: int64

In [16]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [17]:
print(legit.shape)
print(fraud.shape)

(63306, 31)
(165, 31)

In [18]:
legit.Amount.describe()

count    63306.000000
mean        96.084069
std        270.901083
min          0.000000
25%          7.680000
50%         26.270000
75%         87.985000
max      19656.530000
Name: Amount, dtype: float64

In [19]:
fraud.Amount.describe()

count     165.000000
mean       94.772182
std       223.636274
min         0.000000
25%         1.000000
50%         5.300000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [20]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,32886.268884,-0.222052,-0.025881,0.711575,0.157617,-0.252231,0.108458,-0.094471,0.051489,0.054956,...,0.047178,-0.030473,-0.107362,-0.038206,0.006238,0.136169,0.019903,0.000447,0.004078,96.084069
1.0,28970.593939,-7.031319,5.057975,-9.478683,5.499619,-5.201642,-2.141312,-7.386265,3.414395,-3.320945,...,0.421608,0.848637,-0.196178,-0.256211,-0.076312,0.237857,0.116940,0.563026,0.036893,94.772182

In [21]:
legit_sample = legit.sample(n=492)

In [22]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [23]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
166,105,1.175094,0.408263,0.552145,1.255068,-0.196662,-0.565605,0.133973,-0.146202,-0.214155,...,0.130585,0.523640,-0.050125,0.448133,0.597867,-0.275067,0.043308,0.023924,1.00,0.0
30990,36166,-0.214312,0.232435,0.935030,-0.701665,0.118519,-0.593155,0.443049,-0.187489,-1.836874,...,0.325632,0.964564,-0.275201,0.165194,0.013337,0.044373,-0.061059,-0.108054,24.99,0.0
11247,19524,-0.680755,0.321431,2.670685,-1.943573,-0.194176,-0.113570,0.464080,-0.273779,2.712829,...,-0.180910,0.078965,-0.460076,-0.074685,0.397485,-0.876681,-0.387578,-0.397057,15.30,0.0
15446,26825,-1.058172,0.418275,2.044163,0.308964,0.690771,-0.138189,0.719988,-0.110329,0.189517,...,-0.005454,0.320857,-0.373852,0.101831,0.351233,-0.438109,-0.151768,-0.129874,28.70,0.0
54383,46423,-2.481645,0.631048,0.570801,-1.854176,-1.676834,0.028404,-1.420826,1.648125,-1.106681,...,0.493994,1.187497,-0.343748,-0.279757,0.178854,-0.133492,0.322056,-0.066337,69.99,0.0

In [24]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    165
Name: count, dtype: int64

In [25]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,32756.878049,-0.221397,0.136771,0.755417,0.091479,-0.271658,0.075330,-0.049502,-0.015100,0.023909,...,0.038394,-0.007868,-0.086418,-0.028563,0.011464,0.106716,0.007933,-0.023127,-0.004963,81.856606
1.0,28970.593939,-7.031319,5.057975,-9.478683,5.499619,-5.201642,-2.141312,-7.386265,3.414395,-3.320945,...,0.421608,0.848637,-0.196178,-0.256211,-0.076312,0.237857,0.116940,0.563026,0.036893,94.772182

In [26]:
x = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [27]:
print(x)

        Time        V1        V2         V3        V4        V5        V6  \
166      105  1.175094  0.408263   0.552145  1.255068 -0.196662 -0.565605
30990  36166 -0.214312  0.232435   0.935030 -0.701665  0.118519 -0.593155
11247  19524 -0.680755  0.321431   2.670685 -1.943573 -0.194176 -0.113570
15446  26825 -1.058172  0.418275   2.044163  0.308964  0.690771 -0.138189
54383  46423 -2.481645  0.631048   0.570801 -1.854176 -1.676834  0.028404
...      ...       ...       ...        ...       ...       ...       ...
58422  48380 -2.790771 -1.464269   1.031165  1.921356 -0.090014 -0.483871
58761  48533  1.243848  0.524526  -0.538884  1.209196  0.479538 -0.197429
59539  48884 -2.139051  1.394368  -0.612035  1.049327 -1.162102 -0.768219
61787  49985 -1.554216  1.694229  -0.903334  2.425436 -2.899787  0.133028
63421  50706 -8.461845  6.866198 -11.838269  4.194211 -6.923097 -3.221147

             V7        V8        V9  ...       V20       V21       V22  \
166    0.133973 -0.146202 -0.214155  ... -0.116439  0.130585  0.523640
30990  0.443049 -0.187489 -1.836874  ...  0.311181  0.325632  0.964564
11247  0.464080 -0.273779  2.712829  ... -0.079881 -0.180910  0.078965
15446  0.719988 -0.110329  0.189517  ... -0.199952 -0.005454  0.320857
54383 -1.420826  1.648125 -1.106681  ...  0.003919  0.493994  1.187497
...         ...       ...       ...  ...       ...       ...       ...
58422  0.780731 -0.348776  0.609133  ... -1.376721 -0.392667  0.440020
58761  0.049166  0.037792  0.128119  ... -0.171541 -0.051660 -0.084089
59539 -1.997237  0.574997 -0.980832  ...  0.025427  0.696955  0.740003
61787 -0.286226  0.555945 -1.394918  ... -0.032334  0.493436  0.733393
63421 -7.553497  6.015618 -2.466143  ...  0.814710  0.918244 -0.715366

            V23       V24       V25       V26       V27       V28  Amount
166   -0.050125  0.448133  0.597867 -0.275067  0.043308  0.023924    1.00
30990 -0.275201  0.165194  0.013337  0.044373 -0.061059 -0.108054   24.99
11247 -0.460076 -0.074685  0.397485 -0.876681 -0.387578 -0.397057   15.30
15446 -0.373852  0.101831  0.351233 -0.438109 -0.151768 -0.129874   28.70
54383 -0.343748 -0.279757  0.178854 -0.133492  0.322056 -0.066337   69.99
...         ...       ...       ...       ...       ...       ...     ...
58422  0.777659  0.418552  0.244563 -0.159361  0.060540  0.356958  208.58
58761 -0.192846 -0.917392  0.681953 -0.194419  0.045917  0.040136    1.00
59539 -0.155115 -0.050607  0.268368 -0.469433 -0.405814 -0.152171   19.73
61787  0.202350  0.492054 -0.183791 -0.199917  0.395201  0.027693  360.00
63421  0.210747 -0.060211  0.509535 -0.257284  1.170027  0.229301   99.99

[657 rows x 30 columns]

In [28]:
print(y)

166      0.0
30990    0.0
11247    0.0
15446    0.0
54383    0.0
        ...
58422    1.0
58761    1.0
59539    1.0
61787    1.0
63421    1.0
Name: Class, Length: 657, dtype: float64

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [32]:
model = LogisticRegression()

In [33]:
model.fit(x_train, y_train)

LogisticRegression()

In [34]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [35]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9752380952380952

In [36]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [37]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9621212121212122